### ISSUE TITLE
bettet document how ‘self’ argument is handled

### ISSUE THREAD

**Issue by notestaff** [pytest-dev/pluggy#128] opened 2018-03-21 21:34 UTC
It is optional, right? When registering a class with hook impls, the methods can omit the ‘self’ argument and not be @staticmethod , and things will work; in fact, decorating with @staticmethod might cause problems.   Correct?  Would help to clarify the docs.

**Comment by tgoodlet** [comment] 2018-03-21 21:59
Hey @notestaff the implementation for args introspection is [here](https://github.com/pytest-dev/pluggy/blob/master/pluggy/hooks.py#L109).

>When registering a class with hook impls, the methods can omit the ‘self’ argument and not be @staticmethod , and things will work; 

Python will likely throw an error if you tried to do this. But i'm not sure exactly what you mean; provide an example if you want.

>decorating with @staticmethod might cause problems. Correct?

No, afaik this should work fine. 
If not do submit a bug report and test demonstrating the issue :)

I do agree the docs could be better.
I'll put up a PR asap.

**Comment by tgoodlet** [comment] 2018-03-21 22:38
Yeah afaik:

```python
class doggy:
    def bark();
        park

doggy().bark()
```

gives:
```
----> 6 doggy().bark()
TypeError: bark() takes 0 positional arguments but 1 was given
```

So not sure what you mean regarding the no `self` arg without the class func being marked with `staticmethod`/`classmethod`.

**Comment by notestaff** [comment] 2018-03-22 00:38
In https://pluggy.readthedocs.io/en/latest/#call-time-order , SomeOtherPlugin.setup_project() takes no self, and is not marked with staticmethod.

**Comment by nicoddemus** [comment] 2018-03-22 02:25
@notestaff that's a bug in the docs, opened #129 with a fix. Is that enough to close this issue?

**Comment by tgoodlet** [comment] 2018-03-22 15:17
@notestaff yeah definitely just a typo. That code couldn't run in Python as demonstrated above :)

**Comment by notestaff** [comment] 2018-03-22 15:52
maybe also copy the info about self from https://github.com/pytest-dev/pluggy/blob/master/pluggy/hooks.py#L109 to the main docs?  Normally hookimpls can't have args that the hookspec doesn't, but 'self' is an exception to that, correct?

**Comment by tgoodlet** [comment] 2018-04-16 05:15
@nicoddemus mind adding that little extra docs in your PR?

**Closed** 2018-05-18 14:10 UTC

**Comment by pirate** [comment] 2024-09-27 01:56
Is there any way to tell pluggy to leave the methods bound to their original self/class?

i.e. whenever a hookimpl is called, pass the class/self it was originally discovered on to it when running it?

I want to store some static class variables on the classes that are used to namespace my hookimpl, and I'd love for the hook funcs to be able to access their respective class attrs, as it would let you do simple (static/import-time) inheritance e.g.:


`css_plugins.py`:
```python
from pathlib import Path

from my_plugin_system import hookimpl


class DefaultCSSPlugin:
    css_file: Path = 'some/path/to/default.css'

	@hookimpl
    @classmethod
    def get_page_css(cls, page) -> str:
        return Path(cls.css_file).read_text()

class LightModePlugin(DefaultCSSPlugin):
    css_file = 'some/path/to/lightmode.css'

class DarkModePlugin(DefaultCSSPlugin):
    css_file = 'some/path/to/darkmode.css'
```

Example use:
```python
from . import css_plugins

pm.register(css_plugins)

# this would register 3 implementations of get_page_css
```

**Comment by RonnyPfannschmidt** [comment] 2024-09-27 06:14
@pirate your example needs a explanation, it's unclear what you want to happen

**Comment by pirate** [comment] 2024-09-27 09:19
Ah sorry this was a red-herring, the issue I was encountering was actually caused by this: https://github.com/pytest-dev/pluggy/pull/536

Pluggy already preserves the `self`/`class` correctly, I was just confused by the AttributeError and it made me think it was swapping out `self` for something else.
