### ISSUE TITLE
0.12 with importlib_metadata makes it impossible for me to run tests

### ISSUE THREAD

**Issue by mguijarr** [pytest-dev/pluggy#221] opened 2019-06-07 13:10 UTC
Hi all,

I made a StackOverflow issue for this one:

https://stackoverflow.com/questions/56491266/cannot-run-pytest-anymore-because-importlib-metadata-entry-points-fails-with-c

TL, DR: for some reason importlib_metadata cannot return entry points, aborting everything. The exact same project with pluggy==0.11 works fine.

**Comment by nicoddemus** [comment] 2019-06-07 13:44
Hi @mguijarr,

Could you post step by step instructions on how to reproduce this?

**Comment by mguijarr** [comment] 2019-06-07 13:54
Well, it is hard for me to understand what is going wrong.

My workflow is like this:
- my project is installed with "pip install -e ." to have the symlink to be able to edit code without reinstalling each time
- I work, make git commits etc.
- at some point I want to start tests:
    - being in my project's main directory, I start "pytest"
- pytest runs my test suite ; BUT: not with latest pytest with pluggy==0.12 (see error above)

I didn't change anything. The problem comes from importlib_metadata, but I have no clue what I should change/what is wrong with my setup.py or whatever. Was working fine before.

**Comment by nicoddemus** [comment] 2019-06-07 14:17
I was asking more instructions along the lines:

```
$ git clone ...
$ cd ...
$ python3.7 -m venv .env37
$ pip install -e .
$ pytest ...
```

It might seem redundant to provide this, but this answers quite a few questions like which python version you are using, the project URL, which commands you execute which are causing the error, etc. 

This all saves times for us as we don't have to guess and ask follow up questions. 😁 

cc @asottile as he is the expert regarding `importlib-metadata`. 👍

**Comment by asottile** [comment] 2019-06-07 14:35
You have two copies of pytest or some pytest plugin installed (likely with one via easy-install). Try uninstalling each one three times (to make certain it is gone) with pip and then reinstalling

**Comment by asottile** [comment] 2019-06-07 14:36
Or conda + pip, given it seems you're using that

**Comment by mguijarr** [comment] 2019-06-07 15:15
I really appreciate your help guys.

@asottile hmm I have the same behaviour launching tests in a clean, empty Docker environment so I doubt there are multiple pytests. Removing pytest-cov and pytest-mock does not change anything. Uninstalling pytest then reinstalling it does not change anything neither.

Any other idea ?

**Comment by asottile** [comment] 2019-06-07 15:17
can you show your reproduction of a clean docker environment?

**Comment by asottile** [comment] 2019-06-07 15:18
or at least your full `setup.py` / `setup.cfg`?

**Comment by mguijarr** [comment] 2019-06-07 15:22
@asottile sure... I would like to provide a stripped-down, minimal version to allow a fast and easier investigation but unfortunately it is not something I can do in 5 minutes so here is the complete thing as gitlab-ci is doing:

```
$ sudo docker run -it continuumio/miniconda3:latest
$ git clone https://gitlab.esrf.fr/bliss/bliss
$ cd bliss
$ conda config --env --add channels esrf-bcu; conda config --env --append channels conda-forge; conda config --env --append channels tango-controls
$ conda create --quiet --name testenv --file requirements-conda.txt --file requirements-test-conda.txt
$ source activate testenv
$ pip install .
$ pytest
```

**Comment by asottile** [comment] 2019-06-07 15:25
awesome, let me take a look at that -- thanks for providing :)

**Comment by asottile** [comment] 2019-06-07 15:33
interesting, it seems mad about these two lines, this is probably a bug with `importlib-metadata`:

```
[console_scripts]
Bliss = bliss.tango.servers.bliss_ds:main
...
bliss = bliss.shell.cli.main:main
```

this should be an easy fix to importlib-metadata: https://gitlab.com/python-devs/importlib_metadata/merge_requests/76

**Comment by mguijarr** [comment] 2019-06-07 20:55
Thanks a lot !

**Comment by asottile** [comment] 2019-06-07 21:08
closing since this is importlib-metadata territory -- thanks again for the report! glad we could get to the bottom of this and improve it for everyone :tada:

**Closed by asottile** 2019-06-07 21:08 UTC
Labels: bug
