### ISSUE TITLE
Rename misleading function name `PluggyManager.load_setuptools_entrypoints`

### ISSUE THREAD

**Issue by noklam** [pytest-dev/pluggy#440] opened 2023-09-08 15:11 UTC
https://github.com/pytest-dev/pluggy/blob/136bbe8c98b66cbcefdc2438bf3c59705678249b/src/pluggy/_manager.py#L376-L402

From my understanding this works beyond `setuptools`. [PyPa](https://packaging.python.org/en/latest/specifications/entry-points/) suggested that this works for other build tools. From the implementation I can also see that it's not using anything specific to `setuptools`, it is using `importlib`.

Would it make sense to change it to `load_entrypoints`? I am happy to submit a PR if this is desirable. However this will be a breaking change.

**Comment by noklam** [comment] 2023-09-08 15:13
I found this but discussion is outdated. https://github.com/pytest-dev/pluggy/issues/154

**Comment by RonnyPfannschmidt** [comment] 2023-09-08 15:52
There's compatibility shim's and a few pain Points to resolve +downstream usages

So far nobody wanted to incurr that costs on downstreams

**Comment by RonnyPfannschmidt** [comment] 2023-09-08 15:59
Closing as duplicate of #154

**Closed** 2023-09-08 15:59 UTC
