### ISSUE TITLE
Importing pytest_* modules should not trigger PluginValidationError

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pluggy#91] opened 2017-10-05 10:55 UTC
In https://github.com/pytest-dev/pytest-bdd/issues/224 @soulrebel had an issue when [importing `pytest_bdd` in his `conftest.py` file](https://github.com/tierratelematics/cookiecutter-qa/blob/916df0a10f8a934a655b33b8de01d788e851fbb0/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/tests/functional/conftest.py#L4):

```
_pytest.vendored_packages.pluggy.PluginValidationError: unknown hook 'pytest_bdd' in plugin <module 'project_qa.tests.functional.conftest' (<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x7f035b2d4f28>)>
```

This seems odd - importing a `pytest_*` module should work normally, no? Maybe pluggy should at least check that unknown hooks aren't module objects?

**Comment by nicoddemus** [comment] 2017-10-05 11:40
Agreed, thanks

**Comment by tgoodlet** [comment] 2017-11-11 22:42
@The-Compiler looked at this and indeed this should never happen as `PluginManager.register()` always [rejects non-routines](https://github.com/pytest-dev/pluggy/blob/master/pluggy/__init__.py#L260).

I'm not sure how this occurs but it does re-enforce my my thinking we should not allow [registering hookspecs based on project names](https://github.com/pytest-dev/pluggy/blob/master/pluggy/__init__.py#L269) alone and instead should require that all hooks and specs are explicitly marked with decorators.

I'll try to see if I can simulate this with a test.

**Comment by RonnyPfannschmidt** [comment] 2017-11-12 08:36
https://github.com/pytest-dev/pluggy/blob/01d35896e862991f042ebd9e58127f43bdb55b46/pluggy/__init__.py#L241-L256 is responsible for the issue - if we at that bit reject modules/other non-callables while issuing a warning, everything will be fine

**Comment by RonnyPfannschmidt** [comment] 2017-11-12 08:37
going for the future we should turn the hook discovery into policies so we can change them more reasonably

**Comment by tgoodlet** [comment] 2017-11-12 17:53
@RonnyPfannschmidt not sure I agree with that diagnosis ;)

Like I mentioned above the spot where the registration would be rejected is inside the `hookimpl_opts = self.parse_hookimpl_opts(plugin, name)` call at 242 which should reject the opts check with the `inspect.isroutine()` branch. The problem is you guys still haven't de-vendored `pluggy` in mainline `pytest` and [this code doesn't exist in the old vendored version](https://github.com/pytest-dev/pytest/blob/master/_pytest/vendored_packages/pluggy.py#L376)...

My favourite part is that you @RonnyPfannschmidt wrote that code probably to fix this last year around this time hehe.

I've added a test to prove this.

Really like the policy idea btw 👍

**Comment by RonnyPfannschmidt** [comment] 2017-11-12 18:24
#17 lol yes i did that

**Comment by tgoodlet** [comment] 2017-11-12 18:28
@RonnyPfannschmidt @nicoddemus if this isn't motivation to get that de-vendoring done I don't know what is ;)

**Comment by RonnyPfannschmidt** [comment] 2017-11-12 19:31
@tgoodlet the next pytest feature release will

**Comment by nicoddemus** [comment] 2017-11-12 23:31
Definitely we can close this now, thanks @tgoodlet

**Closed by nicoddemus** 2017-11-12 23:31 UTC
Labels: bug
